'use strict';

const { supabaseAdmin } = require('./supabase');
const { storageLogger } = require('../utils/logger');


/**
 * TrustPay Storage Bucket Definitions
 *
 * All file uploads use Supabase Storage — never the local filesystem.
 * Each bucket has a defined purpose, access policy, and file constraints.
 *
 * Bucket naming convention: kebab-case, descriptive, singular-plural where natural.
 */
const STORAGE_BUCKETS = Object.freeze({
  /**
   * User profile photos (avatars).
   * Access: Public — URLs are embedded in UI without auth.
   * Allowed: JPEG, PNG, WebP
   * Max size: 2 MB
   */
  PROFILE_PHOTOS: {
    name: 'profile-photos',
    public: true,
    allowedMimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
    fileSizeLimit: 2 * 1024 * 1024, // 2 MB
    description: 'User profile photos and avatars',
  },

  /**
   * Contract-related document attachments.
   * Access: Private — requires signed URL to access.
   * Allowed: PDF, DOCX, DOC, TXT, PNG, JPEG
   * Max size: 10 MB
   */
  CONTRACT_ATTACHMENTS: {
    name: 'contract-attachments',
    public: false,
    allowedMimeTypes: [
      'application/pdf',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/msword',
      'text/plain',
      'image/png',
      'image/jpeg',
    ],
    fileSizeLimit: 10 * 1024 * 1024, // 10 MB
    description: 'Contract documents and attachments uploaded by clients or workers',
  },

  /**
   * Work evidence submitted by workers for milestone approval.
   * Access: Private — only accessible to contract parties + admin.
   * Allowed: Images, PDF, ZIP, video (for screen recordings)
   * Max size: 50 MB
   */
  WORK_EVIDENCE: {
    name: 'work-evidence',
    public: false,
    allowedMimeTypes: [
      'image/jpeg',
      'image/png',
      'image/webp',
      'image/gif',
      'application/pdf',
      'application/zip',
      'application/x-zip-compressed',
      'video/mp4',
      'video/webm',
    ],
    fileSizeLimit: 50 * 1024 * 1024, // 50 MB
    description: 'Work deliverables and evidence submitted for milestone approvals',
  },

  /**
   * AI or system-generated contract PDFs.
   * Access: Private — shared via signed URL.
   * Allowed: PDF only
   * Max size: 5 MB
   */
  GENERATED_PDFS: {
    name: 'generated-pdfs',
    public: false,
    allowedMimeTypes: ['application/pdf'],
    fileSizeLimit: 5 * 1024 * 1024, // 5 MB
    description: 'Contracts and reports generated by TrustPay (PDFKit)',
  },

  /**
   * Payment invoices and receipts.
   * Access: Private — shared via signed URL.
   * Allowed: PDF only
   * Max size: 5 MB
   */
  INVOICES: {
    name: 'invoices',
    public: false,
    allowedMimeTypes: ['application/pdf'],
    fileSizeLimit: 5 * 1024 * 1024, // 5 MB
    description: 'Payment invoices and transaction receipts',
  },
});

/**
 * Initialize all Supabase Storage buckets.
 *
 * Creates buckets that don't exist yet. Skips existing ones safely.
 * Called during server startup after Supabase connection is verified.
 *
 * @returns {Promise<void>}
 */
async function initializeStorageBuckets() {
  storageLogger.info('Initializing Supabase Storage buckets');

  const results = await Promise.allSettled(
    Object.values(STORAGE_BUCKETS).map(async (bucket) => {
      // Check if bucket already exists
      const { data: existing } = await supabaseAdmin.storage.getBucket(bucket.name);

      if (existing) {
        storageLogger.info('Bucket exists', { bucket: bucket.name });
        return { bucket: bucket.name, status: 'exists' };
      }

      // Create bucket
      const { error } = await supabaseAdmin.storage.createBucket(bucket.name, {
        public: bucket.public,
        allowedMimeTypes: bucket.allowedMimeTypes,
        fileSizeLimit: bucket.fileSizeLimit,
      });

      if (error) {
        throw new Error(`Failed to create bucket '${bucket.name}': ${error.message}`);
      }

      storageLogger.info('Bucket created', { bucket: bucket.name, public: bucket.public });
      return { bucket: bucket.name, status: 'created' };
    })
  );

  // Report any failures (non-fatal — bucket creation can fail if permissions are restricted)
  results.forEach((result) => {
    if (result.status === 'rejected') {
      storageLogger.warn('Storage bucket warning', { message: result.reason.message });
    }
  });

  const succeeded = results.filter((r) => r.status === 'fulfilled').length;
  storageLogger.info('Storage ready', { succeeded, total: Object.keys(STORAGE_BUCKETS).length });
}

/**
 * Generate a signed URL for private bucket access.
 *
 * @param {string} bucket       - Bucket name (use STORAGE_BUCKETS constants)
 * @param {string} path         - File path within the bucket
 * @param {number} [expiresIn]  - URL expiry in seconds (default: 3600 = 1 hour)
 * @returns {Promise<string>}   - Signed URL
 */
async function getSignedUrl(bucket, path, expiresIn = 3600) {
  const { data, error } = await supabaseAdmin.storage
    .from(bucket)
    .createSignedUrl(path, expiresIn);

  if (error) {
    throw new Error(`Failed to generate signed URL: ${error.message}`);
  }

  return data.signedUrl;
}

/**
 * Get a public URL for public buckets.
 *
 * @param {string} bucket - Bucket name
 * @param {string} path   - File path within the bucket
 * @returns {string}      - Public URL (no expiry)
 */
function getPublicUrl(bucket, path) {
  const { data } = supabaseAdmin.storage.from(bucket).getPublicUrl(path);
  return data.publicUrl;
}

module.exports = {
  STORAGE_BUCKETS,
  initializeStorageBuckets,
  getSignedUrl,
  getPublicUrl,
};
